version: '2'

services:
  drone-server:
    image: drone/drone:1.6.5
    container_name: drone
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    environment:
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GITLAB_SERVER=${DRONE_GITLAB_SERVER}
      - DRONE_GITLAB_CLIENT_ID=${DRONE_GITLAB_CLIENT_ID}
      - DRONE_GITLAB_CLIENT_SECRET=${DRONE_GITLAB_CLIENT_SECRET}
      - DRONE_RUNNER_CAPACITY=5
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_TLS_AUTOCERT=true
      - DRONE_HTTP_SSL_REDIRECT=true
      - DRONE_HTTP_SSL_TEMPORARY_REDIRECT=true
